### ISSUE TITLE
IDEA - ship direction indicator

### ISSUE THREAD

**Issue by IanisPeein** [deferred-impact/aim-issue-tracker#12]
kind of a handicap feature, similar to stug it basically shows what direction the ship is actually pointing along with the actual mouse location

i guess this just makes the game more friendly to noobs and people with bad ping

**Comment by deferred-impact** [comment]
I don't understand the request. Let's say your ping is 100ms. The game is always showing "what direction the ship was actually pointing" 100ms ago.

**Comment by IanisPeein** [comment]
i might be dumb, does the ship turn to your mouse direction immediately, cuz nevermind then

**Comment by deferred-impact** [comment]
No, the ship has a maximum turning speed which is relatively slow. It's just that... i thought the ship itself would work just fine to point where the ship is pointing. I mean come on, it's shaped like a fucking arrow. What else do you want? A line that goes from the nose of the ship and into the infinity?

**Comment by IanisPeein** [comment]
its hard sometimes yk

the thing in stug made it a lot easier to aim

**Comment by deferred-impact** [comment]
Okay, fair enough. I see what you want. I will add it.

**Comment by IanisPeein** [comment]
yo wtf w

**Comment by deferred-impact** [comment]
:3
