### ISSUE TITLE
basic match system

### ISSUE THREAD

**Issue by IanisPeein** [deferred-impact/aim-issue-tracker#15]
add kill counts by names, with a basic timer at the top of the screen which resets kill counts and regenerates the map once it reaches 0 

alternatively just some way to track kills and deaths

**Comment by deferred-impact** [comment]
Map is regenerated once every 4 hours. I think that is fine as is; it offers the best balance between freshness and familiarity.

Yeah i suppose adding some score wouldn't be bad. I'm actually thinking about adding a KPM stat instead, averaged over the last 10 minutes. At least for now. In future we'll have more complex and advanced scoring systems.
