### ISSUE TITLE
railgun preview is scuffed

### ISSUE THREAD

**Issue by IanisPeein** [deferred-impact/aim-issue-tracker#16]
the preview and shot are not the same length

also the end of the railgun shot is kinda jarring, maybe fade it out or blur the end slightly

**Comment by deferred-impact** [comment]
I don't see a big issue with the preview and shot being a different length... the preview merely exists to show that yes, the railgun has been queried and will fire in that direction. That said, i guess it's not hard to fix.

Yes. The railgun and cast graphics will be updated very soon.

**Comment by deferred-impact** [comment]
Would you consider this fixed? @IanisPeein

**Comment by IanisPeein** [comment]
pretty much
