### ISSUE TITLE
weapon selections reset on new launch

### ISSUE THREAD

**Issue by IanisPeein** [deferred-impact/aim-issue-tracker#18]
when i reopen the game after a while it shows my previous weapon selections, but in game i have the defaults (direct impact and whatever)

might be some server thing idk

issue is fixed by any interaction with the weapon select screen

**Comment by deferred-impact** [comment]
Yeah just bad sync code. I think i know how to fix this

**Comment by deferred-impact** [comment]
This should be fixed @IanisPeein let me know if you run into this again
