### ISSUE TITLE
cast explosions

### ISSUE THREAD

**Issue by IanisPeein** [deferred-impact/aim-issue-tracker#20]
not super important fix, but having DIE CAST and CAST DOUBT keep showing the circle while the explosion animation is playing

this is because people will complain if the hitbox is unclear and they die

also its kinda hard to tell when u got hit by cast doubt

**Comment by deferred-impact** [comment]
I don't understand - the circle is there with the explosion

**Comment by IanisPeein** [comment]
like visible to ur enemies? i thought just the particles showed up

**Comment by deferred-impact** [comment]
Yes the explosion effect includes the circle

**Comment by IanisPeein** [comment]
nvm then
