### ISSUE TITLE
make names smaller?

### ISSUE THREAD

**Issue by IanisPeein** [deferred-impact/aim-issue-tracker#24]
they are unnecessarily big

and you can track offscreen players cuz theyre so big

maybe just center it above the player and make it smaller

**Comment by deferred-impact** [comment]
1. You say they are unnecessarily big then go on to complain about the UI being too small. Pick one
2. I don't really see a problem with tracking offscreen players? In fact i might want to add an offscreen player indicator
3. Centering might be a good idea maybe

**Comment by IanisPeein** [comment]
the ui is too small and the name is too big yes

**Comment by IanisPeein** [comment]
the ui from the weapon screen is small and the names dont need to be as big
