### ISSUE TITLE
scoreboard

### ISSUE THREAD

**Issue by IanisPeein** [deferred-impact/aim-issue-tracker#28]
make scorboard appear while respawning

maybe add kills and deaths? the score thing is super hard to interpret

**Comment by IanisPeein** [comment]
also a graph for the score would be pretty cool cuz it fluctuates a lot

not really needed for kills and deaths tho since they accumulate

**Comment by deferred-impact** [comment]
I will make it show while respawning, sure, that's trivial.

I could make it also show the kills and deaths. My only issue with that, i fear people will straight up ignore the score and only care about kills. I don't want that. Between a player with 50K/1D and 100K/10D, who is the better player? Judging by kills - which is what dumbstupid people like the ones who grind KPG in battledudes.io would do - results in a straight up wrong answer.

A graph is an interesting and cool idea, but is a massive pain in the ass to implement. So don't count on it.

No, Ian, kills and deaths don't accumulate. Hilariously shows how much you don't understand the scoring system. The game only tracks the last 10 minutes. Your kills and deaths expire.

I would appreciate it if you didn't bundle several related but completely different suggestions into a single issue from this point onwards. Create a new issue it's not that hard.

**Comment by IanisPeein** [comment]
you didnt understand my last bit i think but its ok

**Comment by deferred-impact** [comment]
Well if i didn't understand, you should elaborate.

**Comment by IanisPeein** [comment]
i agree with u
