### ISSUE TITLE
add chanelog to game

### ISSUE THREAD

**Issue by IanisPeein** [deferred-impact/aim-issue-tracker#37]

**Comment by deferred-impact** [comment]
Don't see the point?

**Comment by IanisPeein** [comment]
ok low priority
just easier for people to find it then

**Comment by deferred-impact** [comment]
Zero priority as far as i'm concerned. People who care about the changelog, will find it. 99% of people couldn't give less of a shit.

**Comment by IanisPeein** [comment]
thats true
