### ISSUE TITLE
parries abusable

### ISSUE THREAD

**Issue by IanisPeein** [deferred-impact/aim-issue-tracker#55]
just shoving 2 in the bottom 2 slots, you can just cycle between them, and if you hold down shift and space you just get free invincibility while you can shoot normally

**Comment by deferred-impact** [comment]
I don't see a way to fix this without removing parries completely. Do you?

**Comment by IanisPeein** [comment]
no xd

**Comment by deferred-impact** [comment]
Shouldn't be an issue anymore, yes?

**Comment by IanisPeein** [comment]
its better now
